name: Build, Test and E2E

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-test:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:20.10-dind
                options: --privileged

        steps:
            # ----------------- Checkout -----------------
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------- Set up Docker Buildx -----------------
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # ----------------- Criar arquivo .env dinamicamente -----------------
            - name: Criar arquivo .env para backend
              run: |
                  mkdir -p backend
                  cat <<EOF > backend/.env
                  POSTGRES_DB=adote_facil
                  POSTGRES_HOST=adote-facil-postgres
                  POSTGRES_USER=postgres
                  POSTGRES_PASSWORD=postgres
                  POSTGRES_PORT=5432
                  POSTGRES_CONTAINER_PORT=6500
                  DATABASE_URL="postgresql://postgres:postgres@adote-facil-postgres:5432/adote_facil?schema=public"
                  JWT_SECRET="secret"
                  EOF

            # ----------------- Build e start containers -----------------
            - name: Build and start containers
              run: docker compose --env-file backend/.env up -d --build

            # ----------------- Esperar serviços com dockerize -----------------
            - name: Esperar frontend, backend e Postgres
              run: |
                  apk add --no-cache dockerize
                  dockerize -wait tcp://localhost:3000 -timeout 60s
                  dockerize -wait tcp://localhost:4000 -timeout 60s
                  dockerize -wait tcp://localhost:6500 -timeout 60s

            # ----------------- Rodar Cypress -----------------
            - name: Instalar dependências Cypress
              run: npm install cypress --save-dev

            - name: Rodar testes E2E
              run: npx cypress run --config baseUrl=http://localhost:3000

            # ----------------- Encerrar containers -----------------
            - name: Stop containers
              run: docker compose down
