name: Build, Test and E2E

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-test:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:20.10-dind
                options: --privileged

        steps:
            # ----------------- Checkout -----------------
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------- Set up Docker Buildx -----------------
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # ----------------- Build e start containers usando .env existente -----------------
            - name: Build and start containers
              run: docker compose --env-file backend/.env up -d --build

            # ----------------- Esperar serviços com dockerize -----------------
            - name: Esperar frontend, backend e Postgres
              run: |
                  apk add --no-cache dockerize
                  dockerize -wait tcp://localhost:3000 -timeout 60s
                  dockerize -wait tcp://localhost:4000 -timeout 60s
                  dockerize -wait tcp://localhost:6500 -timeout 60s   # porta do Postgres do .env

            # ----------------- Rodar Cypress -----------------
            - name: Instalar dependências Cypress
              run: npm install cypress --save-dev

            - name: Rodar testes E2E
              run: npx cypress run --config baseUrl=http://localhost:3000

            # ----------------- Encerrar containers -----------------
            - name: Stop containers
              run: docker compose down
